version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - backend

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - type: bind
        source: /datalake/nextcloud
        target: /var/www/html
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - backend
      - default

volumes:
  db:

networks:
  backend: