version: '3'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    env_file:
      - plex.env
    network_mode: host
    volumes:
      - /datalake/plex/database:/config
      - /datalake/plex/transcode:/transcode
      - /datalake/plex/media:/data