apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: server-sadness
  name: server-sadness
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: server-sadness
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server-sadness
    spec:
      containers:
      - image: nginx
        name: server-sadness
        ports:
        - containerPort: 80
        volumeMounts:
        - name: server-sadness-configmap
          mountPath: /usr/share/nginx/html
      volumes:
      - name: server-sadness-configmap
        configMap:
          name: server-sadness-configmap